auteur = "Emma Goldman"
author = "Emma Goldman"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/uploads/tailpiece.jpg"
description = "A contemporary text"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "images/logo.png"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = ""
titre = "Anarchism and Other Essays"
