auteur = "Edgar Allan Poe"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/uploads/couverture.png"
description = "Une édition collaborative"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "images/logo.jpg"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Édition partielle des Nouvelles histoires extraordinaires"
titre = "La Fabrique de Poe"
