DefaultContentLanguage = "fr"
baseURL = ""
theme = "epub"

disableKinds = ["RSS", "robotsTXT", "404", "taxonomy", "section", "term", "sitemap"]

languageCode = "fr-fr"

uglyurls = true
relativeURLs = true
disablePathToLower = true

minify = false
paginate = 999
pygmentsCodeFences = false
pygmentsUseClasses = false

[outputs]
    home = ["OPF","NCX"]
    page = ["XHTML"]

[permalinks]
    pages = "/content/:filename"
    #posts = "/:filename"
# add your section name(s) here. Default is "blog"
    posts = "/content/:filename"
    "/" = "/content/:filename"

[mediaTypes]
  [mediaTypes."application/xhtml+xml"]
    suffixes = ["xhtml"]
  [mediaTypes."application/opf+xml"]
    suffixes = ["opf"]
  [mediaTypes."application/x-dtbncx+xml"]
    suffixes = ["ncx"]
    
[outputFormats]
  [outputFormats.XHTML]
    mediaType = "application/xhtml+xml"
    isHTML = true
    permalinkable = true
  [outputFormats.OPF]
    mediaType = "application/opf+xml"
    isHTML = true
    permalinkable = true
    path = "content"
    baseName = "content"
  [outputFormats.NCX]
    mediaType = "application/x-dtbncx+xml"
    isHTML = true
    permalinkable = true
    path = "content"
    baseName = "toc"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = false
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = false
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = true

ignorefiles = [ "static/admin", "static/plugins", "static/fonts", "static/images" ]
