audience = "adult"
author = "Emma Goldman"
bookid = ""
copyright = "CC BY-NC-SA"
creator = "Emma Goldman"
description = "A contemporary text"
imgsize = "1200x q70"
logo = ""
publisher = "Fabrique"
subject = ["essay", "anarchism"]
subtitle = "A contemporary text"
title = "Anarchism and Other Essays"
titre = "Anarchism and Other Essays"
