name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

stages:
  - pre-build
  - build
  - post-build
  - site

hugo2:
  stage: pre-build
  image: jojomi/hugo
  script:
  - hugo version
  - hugo --cleanDestinationDir --environment epub --destination temp
  artifacts:
    paths:
    - temp
  only:
  - main
zip:
  stage: build
  image: tetraweb/php
  script:
  - apt-get update
  - apt-cache gencaches
  - apt-get install -y zip unzip
  - cd temp
  - rm -f ebook.epub
  - zip -rX ebook.epub mimetype content META-INF uploads
  artifacts:
    paths:
    - temp
  only:
  - main
hugo1:
  stage: post-build
  image: jojomi/hugo
  script:
  - hugo version
  - hugo --environment _default --destination temp2
  artifacts:
    paths:
    - temp2
  only:
  - main
pages:
  stage: site
  image: alpine:latest
  script:
  - mkdir -p public
  - cp temp/ebook.epub public
  - cp -r temp2/* public
  artifacts:
    paths:
    - public
  only:
    - main